name: tawwon
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  motion_toast: ^2.6.7
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts: 
    - family: ReadexPro
      fonts: 
        - asset: assets/fonts/ReadexPro.ttf

  assets:
    - assets/images/

  
